name: CI_PR
on:
  pull_request:
    branches:
      - main

# Build PR code without write permissions or deployment secrets.
permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Update theme
        # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
        run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.83.1"
          extended: true

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo --minify

      - name: Upload built site
        uses: actions/upload-artifact@v6
        with:
          name: netlify-preview
          path: public/
          if-no-files-found: error
          retention-days: 7
